# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"compute": "00_core.ipynb",
         "multi": "01_core.ipynb"}

modules = ["core.py"]

doc_url = "https://wwnew.github.io/nbdev_test/"

git_url = "https://github.com/wwnew/nbdev_test/tree/master/"

def custom_doc_links(name): return None
