# AUTOGENERATED! DO NOT EDIT! File to edit: 01_core.ipynb (unless otherwise specified).

__all__ = ['combined_cos', 'say_hello', 'HelloSayer']

# Cell
def combined_cos(pct, start, middle,end):
    "return a scleduler with cosine annealing from 'start'->'middle'&'middle'->'end'"
    return combined_scheds([pct,1-pct],[SchedCos(start,middle),SchedCos(midle,end)])

# Cell
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# Cell
class HelloSayer:
    "Say hello to `to` using `say_hello`"
    def __init__(self, to): self.to = to
    def say(self):
        "哈哈哈哈哈O(∩_∩)Ohelooooooo"
        say_hello(self.to)