# AUTOGENERATED! DO NOT EDIT! File to edit: 01_core.ipynb (unless otherwise specified).

__all__ = ['combined_cos']

# Cell
def combined_cos(pct, start, middle,end):
    "return a scleduler with cosine annealing from 'start'->'middle'&'middle'->'end'"
    return combined_scheds([pct,1-pct],[SchedCos(start,middle),SchedCos(midle,end)])
